languageCode = "en-us"
title = "MakeoverMonday 2018 - CW 39"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.en]
  languageName = "English"
#[languages.es]
#  languageName = "Español"
#  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
